use campfire::commands::{build_snippet_shell_command, render_shell_functions};
use campfire::config::CampfireConfig;

#[test]
fn appends_shell_quoted_args_to_snippets() {
    let config: CampfireConfig = toml::from_str(
        r#"
[campfire]
image = "fedora"

[commands.gs]
run = "git status"
"#,
    )
    .expect("config parses");

    let command = build_snippet_shell_command(
        &config.commands["gs"],
        &["-sb".to_string(), "it's".to_string()],
    );

    assert_eq!(command, "git status '-sb' 'it'\\''s'");
}

#[test]
fn renders_shell_functions_for_configured_commands() {
    let config: CampfireConfig = toml::from_str(
        r#"
[campfire]
image = "fedora"

[commands.gs]
run = "git status"
description = "Show status"

[commands.versions]
run = "cat /etc/alpine-release && busybox | head -n 1"
"#,
    )
    .expect("config parses");

    let script = render_shell_functions(&config.commands);

    assert!(script.contains("# Generated by Campfire."));
    assert!(script.contains("# Show status"));
    assert!(script.contains("gs() {\n    git status \"$@\"\n}"));
    assert!(
        script
            .contains("versions() {\n    cat /etc/alpine-release && busybox | head -n 1 \"$@\"\n}")
    );
}
