use std::collections::BTreeMap;

use crate::config::CommandSnippet;

pub fn build_snippet_shell_command(snippet: &CommandSnippet, args: &[String]) -> String {
    if args.is_empty() {
        return snippet.run.clone();
    }

    let mut command = snippet.run.clone();
    for arg in args {
        command.push(' ');
        command.push_str(&shell_quote(arg));
    }
    command
}

pub fn render_shell_functions(commands: &BTreeMap<String, CommandSnippet>) -> String {
    let mut script = "# Generated by Campfire.\n".to_string();

    for (name, command) in commands {
        if let Some(description) = &command.description {
            for line in description.lines() {
                script.push_str("# ");
                script.push_str(line);
                script.push('\n');
            }
        }

        script.push_str(name);
        script.push_str("() {\n    ");
        script.push_str(&command.run);
        script.push_str(" \"$@\"\n}\n");
    }

    script
}

fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }

    let mut quoted = String::from("'");
    for character in value.chars() {
        if character == '\'' {
            quoted.push_str("'\\''");
        } else {
            quoted.push(character);
        }
    }
    quoted.push('\'');
    quoted
}
